# Pre-commit hooks configuration for RallyCal
# See https://pre-commit.com for more information

repos:
  # Ruff linting and formatting (replaces black, isort, flake8, etc.)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        name: ruff (linter)
        args: [--fix]
        types_or: [python, pyi]
      - id: ruff-format
        name: ruff (formatter)
        types_or: [python, pyi]

  # Type checking with mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        name: mypy (type checker)
        additional_dependencies:
          - types-PyYAML
          - sqlmodel
          - fastapi
          - httpx
          - icalendar
          - pydantic-settings
        args: [--config-file=pyproject.toml]

  # Basic file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        name: trim trailing whitespace
      - id: end-of-file-fixer
        name: fix end of files
      - id: check-yaml
        name: check yaml files
        args: [--unsafe]  # Allow custom YAML tags
      - id: check-toml
        name: check toml files
      - id: check-json
        name: check json files
      - id: check-added-large-files
        name: check for added large files
        args: [--maxkb=1024]
      - id: check-merge-conflict
        name: check for merge conflicts
      - id: check-case-conflict
        name: check for case conflicts

  # Security scanning
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.10
    hooks:
      - id: bandit
        name: bandit (security linter)
        args: [-c, pyproject.toml]
        additional_dependencies: [bandit[toml]]

  # SQL formatting for migrations
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.2.5
    hooks:
      - id: sqlfluff-lint
        name: sqlfluff (sql linter)
        files: \.(sql)$
        args: [--dialect=sqlite]
      - id: sqlfluff-fix
        name: sqlfluff (sql formatter)
        files: \.(sql)$
        args: [--dialect=sqlite]

  # Dockerfile linting
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        name: hadolint (dockerfile linter)

  # Shell script linting
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
      - id: shellcheck
        name: shellcheck (shell linter)

# Global configuration
default_stages: [commit, push]
fail_fast: false
minimum_pre_commit_version: "3.5.0"

# CI configuration
ci:
  autofix_prs: true
  autofix_commit_msg: "style: auto-fixes from pre-commit hooks"
  autoupdate_branch: "main"
  autoupdate_commit_msg: "chore: update pre-commit hooks"
  autoupdate_schedule: weekly
  skip: [mypy]  # Skip mypy in CI since it requires dependencies